### ISSUE TITLE
Intermittent callout test failures 

### ISSUE THREAD

**Issue by jonner** [mdevctl/mdevctl#64]
When building fedora packages for the new release, Alex Williamson reported random failures of the callout tests:

https://koji.fedoraproject.org/koji/taskinfo?taskID=90510322
https://koji.fedoraproject.org/koji/taskinfo?taskID=90510630

See merge request #55 for previous callout test failures...

**Comment by jonner** [comment]
@awilliam Unfortunately, I'm unable to find a cause as of yet. I also tried doing a few scratch builds and none of them failed. It would help to diagnose the issue if the tests were run with RUST_BACKTRACE=1 and MDEVCTL_LOG=debug.

**Comment by awilliam** [comment]
Not sure how to do that via kodi, nor do I have any reliable means to reproduce.  I've gone ahead and pushed to f35 and f36 testing, where both builds completed w/o spurious errors.

**Comment by jonner** [comment]
I just managed to reproduce this in a f36 container with those environment variables set (perhaps we should add them to the %check section of the spec file):

```running 10 tests
test tests::test_stop ... ok
test tests::test_invalid_files ... ok
test tests::test_load_json ... ok
test tests::test_undefine ... ok
test tests::test_types ... ok
test tests::test_modify ... ok
test tests::test_callouts ... FAILED
test tests::test_define ... ok
test tests::test_start ... ok
test tests::test_list ... ok

failures:

---- tests::test_callouts stdout ----
[2022-08-16T16:47:35Z INFO  mdevctl::tests] ---- Running test 'callouts/test_callout_all_success' ----
[2022-08-16T16:47:35Z DEBUG mdevctl::callouts] pre-test: looking for a matching callout script for dev type 'test_type'
[2022-08-16T16:47:35Z DEBUG mdevctl::callouts] pre-test: executing "/tmp/mdevctl-test18jMLS/etc/mdevctl.d/scripts.d/callouts/rc0.sh"
[2022-08-16T16:47:35Z DEBUG mdevctl::callouts] found callout script "/tmp/mdevctl-test18jMLS/etc/mdevctl.d/scripts.d/callouts/rc0.sh"
[2022-08-16T16:47:35Z DEBUG mdevctl::callouts] post-test: executing "/tmp/mdevctl-test18jMLS/etc/mdevctl.d/scripts.d/callouts/rc0.sh"
[2022-08-16T16:47:35Z DEBUG mdevctl::callouts] notify-test: executing notification scripts for device 976d8cc2-4bfc-43b9-b9f9-f4af2de91ab9
[2022-08-16T16:47:35Z INFO  mdevctl::tests] ---- Running test 'callouts/test_callout_all_fail' ----
[2022-08-16T16:47:35Z DEBUG mdevctl::callouts] pre-test: looking for a matching callout script for dev type 'test_type'
[2022-08-16T16:47:35Z DEBUG mdevctl::callouts] pre-test: executing "/tmp/mdevctl-testC7YQQU/etc/mdevctl.d/scripts.d/callouts/rc1.sh"
[2022-08-16T16:47:35Z DEBUG mdevctl::callouts] failed to execute callout script "/tmp/mdevctl-testC7YQQU/etc/mdevctl.d/scripts.d/callouts/rc1.sh": Text file busy (os error 26)
    
    Stack backtrace:
       0: anyhow::error::<impl core::convert::From<E> for anyhow::Error>::from
                 at /usr/share/cargo/registry/anyhow-1.0.59/src/error.rs:533:25
       1: <core::result::Result<T,F> as core::ops::try_trait::FromResidual<core::result::Result<core::convert::Infallible,E>>>::from_residual
                 at /builddir/build/BUILD/rustc-1.63.0-src/library/core/src/result.rs:2125:27
       2: mdevctl::callouts::Callout::invoke_script
                 at ./src/callouts.rs:197:25
       3: mdevctl::callouts::Callout::invoke_first_matching_script
                 at ./src/callouts.rs:243:19
       4: mdevctl::callouts::Callout::callout
                 at ./src/callouts.rs:282:17
       5: mdevctl::callouts::Callout::invoke
                 at ./src/callouts.rs:100:19
       6: mdevctl::tests::test_invoke_callout
                 at ./src/tests.rs:1514:15
       7: mdevctl::tests::test_callouts
                 at ./src/tests.rs:1557:5
       8: test::__rust_begin_short_backtrace
       9: test::run_test::run_test_inner::{{closure}}
      10: std::sys_common::backtrace::__rust_begin_short_backtrace
      11: core::ops::function::FnOnce::call_once{{vtable.shim}}
      12: std::sys::unix::thread::Thread::new::thread_start
      13: start_thread
      14: __clone3
[2022-08-16T16:47:35Z DEBUG mdevctl::callouts] post-test: looking for a matching callout script for dev type 'test_type'
[2022-08-16T16:47:35Z DEBUG mdevctl::callouts] post-test: executing "/tmp/mdevctl-testC7YQQU/etc/mdevctl.d/scripts.d/callouts/rc1.sh"
[2022-08-16T16:47:35Z DEBUG mdevctl::callouts] found callout script "/tmp/mdevctl-testC7YQQU/etc/mdevctl.d/scripts.d/callouts/rc1.sh"
[2022-08-16T16:47:35Z DEBUG mdevctl::callouts] Error occurred when executing post callout script
[2022-08-16T16:47:35Z DEBUG mdevctl::callouts] notify-test: executing notification scripts for device 976d8cc2-4bfc-43b9-b9f9-f4af2de91ab9
thread 'tests::test_callouts' panicked at 'Expected invoke callout to fail: ()', src/tests.rs:25:25
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: core::result::Result<T,E>::expect_err
             at /builddir/build/BUILD/rustc-1.63.0-src/library/core/src/result.rs:1163:22
   4: mdevctl::tests::assert_result
             at ./src/tests.rs:25:21
   5: mdevctl::tests::test_invoke_callout
             at ./src/tests.rs:1515:13
   6: mdevctl::tests::test_callouts
             at ./src/tests.rs:1557:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    tests::test_callouts

test result: FAILED. 9 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.04s

error: test failed, to rerun pass '--bin mdevctl'
error: Bad exit status from /var/tmp/rpm-tmp.lzU9BU (%check)

RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.lzU9BU (%check)
```

The interesting bit seems to be this:
`[2022-08-16T16:47:35Z DEBUG mdevctl::callouts] failed to execute callout script "/tmp/mdevctl-testC7YQQU/etc/mdevctl.d/scripts.d/callouts/rc1.sh": Text file busy (os error 26)`

Each test runs in its own temporary filesystem environment, and these callout scripts are copied into this per-test environment. So it seems that when we attempt to execute the callout script, that file may be opened and writable from elsewhere.

**Comment by jonner** [comment]
It looks like we're probably hitting the same issue described here: https://github.com/golang/go/issues/22315. Cargo's test suite is by default multi-threaded. So if test thread A forks (e.g. to execute a callout script) while test thread B is in the middle of copying a callout script file into its temporary test environment, that fork will hold an open writeable file descriptor to the callout script which will result in the ETXTBSY error when thread B attempts to execute that callout script.

**Comment by jonner** [comment]
I made a little script to just run the test suite repeatedly until there was a failure. With the current upstream code, it averages about 900 iterations before a failure (N=6). 

When I change the code of the test suite so that I fork before copying the callout scripts, it did 107,000 iterations without a failure. That seems to confirm that the issue is the same one referenced in my previous comment. When we do the copy in a child process, there is no longer a writeable file handle open in the parent that can be inherited by other child processes, so the ETXTBSY error doesn't happen. It seems unfortunate to fork a new process just to copy some files, but I'm not sure what the alternative is. And at least it only affects the test suite.

Here's the patch I used in my test:

````diff
diff --git a/Cargo.toml b/Cargo.toml
index 0ec6a65..de36eba 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -24,3 +24,7 @@ tempfile = "3"
 clap = { version = "3.1.18", features = ["derive"]}
 clap_complete = "3.0.6"
 uuid = "1.0"
+
+[dev-dependencies]
+nix = "0.25.0"
+libc = "0.2"
diff --git a/src/tests.rs b/src/tests.rs
index 8c6c50e..cd3be93 100644
--- a/src/tests.rs
+++ b/src/tests.rs
@@ -104,7 +104,18 @@ impl TestEnvironment {
         assert!(calloutscript.exists());
 
         let dest = self.callout_dir().join(filename);
-        fs::copy(calloutscript, dest).expect("Unable to copy callout script");
+        use nix::unistd::ForkResult;
+        match unsafe {nix::unistd::fork()}.expect("failed to fork") {
+            ForkResult::Parent { child } => {
+                println!("parent");
+                nix::sys::wait::waitpid(child, None).expect("Failed to wait for child");
+            },
+            ForkResult::Child => {
+                println!("child");
+                fs::copy(calloutscript, &dest).expect("Unable to copy callout script");
+                unsafe { libc::_exit(0); }
+            }
+        }
     }
 
     // set up a few files in the test environment to simulate a parent device that supports
````
